name: Run cypress tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20, 18.16, 19.9]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - working-directory: .
        run: npm install
      - working-directory: .
        run: npm run build
      - working-directory: .
        run: npm test
        env:
          CI: true
